### ISSUE TITLE
Add support for "move" operation

### ISSUE THREAD

**Issue by sergkr** [myquay/JsonPatch#11]
I noticed there's no support yet for the [move](https://tools.ietf.org/html/rfc6902#section-4.4) operation. This would be highly useful when trying to express the operation of [moving an array element](https://tools.ietf.org/html/rfc6902#appendix-A.7) (though that's not the only use case):

    An example target JSON document:
    
    { "foo": [ "all", "grass", "cows", "eat" ] }
    
    A JSON Patch document:
    
    [
      { "op": "move", "from": "/foo/1", "path": "/foo/3" }
    ]
    
    The resulting JSON document:
    
    { "foo": [ "all", "cows", "eat", "grass" ] }

Would you be open to a pull request on this?  I can try to take a stab at it, unless this is something you would rather take a look at yourself.

**Comment by mindingdata** [comment]
I say take a stab at it, it's not a bad thing to implement more functionality of the actual RFC. 

I only question the useability of something like this. How often will a client actually send a move request? I think the majority of requests coming through would be from Diff of two objects. A small number may be off add or removal of arrays. e.g. You have a list of something, and the user clicks a button to "Add another item", you can send the add command. 

I suppose the only usecase would be for real time saving of a list sorting instead of saving right at the end?

**Comment by myquay** [comment]
I'm definitely open to a pull request on this, I'm not opposed to implementing more of the RFC. Although I see it as more of a nice to have than essential functionality.

**Comment by sergkr** [comment]
I'll take a look at this as well.

> I suppose the only usecase would be for real time saving of a list sorting instead of saving right at the end?

The use case I was thinking of for the project I'm currently working on (an "advanced" quiz editor) is pretty much exactly this. Users have the ability to reorder questions using drag-and-drop - when the order is changed, I would like to issue a PATCH request from the client, and I don't want that request to have to include the entire list if all they're doing is swapping two items.

I agree the majority of operations would be to add/remove, so this probably isn't as essential - but it's highly useful in a scenario like that one.

**Comment by myquay** [comment]
Resolved as part of #14 - nice one.
