### ISSUE TITLE
"add" should not instantiate objects or arrays for intermediate parts of the path

### ISSUE THREAD

**Issue by sergkr** [myquay/JsonPatch#12]
I'm currently working on implementing "move" for #11 and noticed something about how "add" (and possibly "remove") are implemented. In [`PathHelper.SetValueFromPath()`](https://github.com/myquay/JsonPatch/blob/master/src/JsonPatch/Helpers/PathHelper.cs#L49), as we're traversing the path, we're instantiating objects and creating arrays as we go:

    //If we're still traversing the path, make sure we've instantiated objects along the way
    var propertyValue = property.GetValue(entity);
    var propertyType = property.PropertyType;

    if (propertyValue == null)
    {
        if (property.PropertyType.IsArray)
        {
            propertyValue = Activator.CreateInstance(property.PropertyType, new object[] { 0 });
        }
        else
        {
            propertyValue = Activator.CreateInstance(property.PropertyType);
        }
    }

    propertyValue = SetValueFromPath(propertyType, String.Join("/", pathComponents.Skip(1)), propertyValue, value, operationType);
    property.SetValue(entity, propertyValue);

I'm not sure that's valid, per the spec. We should only be setting values / adding array entries at the target path (the final destination) - we should not be setting any properties or instantiating arrays for any intermediate parts of the path.

Here's the relevant part of the spec (towards the end of [4.1](https://tools.ietf.org/html/rfc6902#section-4.1)):

    However, the object itself or an array containing it does need to
    exist, and it remains an error for that not to be the case.  For
    example, an "add" with a target location of "/a/b" starting with this
    document:

    { "a": { "foo": 1 } }

    is not an error, because "a" exists, and "b" will be added to its
    value.  It is an error in this document:

    { "q": { "bar": 2 } }

    because "a" does not exist.

Based on the above, I don't think this test case is valid:

    [TestMethod]
    public void SetValueFromPath_AddToEmptyArray_CreatesArrayAndAddsValue()
    {
        //arrange
        var entity = new ComplexEntity { };

        //act
        PathHelper.SetValueFromPath(typeof(ComplexEntity), "/Foo/Foo/0", entity, "Element One", JsonPatchOperationType.add);

        //assert
        Assert.IsNotNull(entity.Foo);
        Assert.IsNotNull(entity.Foo.Foo);
        Assert.AreEqual(1, entity.Foo.Foo.Length);
        Assert.AreEqual("Element One", entity.Foo.Foo[0]);
    }

Let me know if I might have misinterpreted the spec or the code (it is late).  Assuming I understood everything correctly, should I just go ahead and roll the fix for this into the same pull request as for #11 (would be easier, as I'll be making major changes to the PathHelper class anyway)?.

**Comment by mindingdata** [comment]
OK so just trying to wrap my head around this. Is this example correct?

```
Existing object : 
{ "q": { "bar": 2 } }

Destination "state" : 
{ "q": { "bar": 2 }, "a" : { "b" : "123"} }

Current code usage : 
[
{ "op" : "add", "path" : "/a/b", "value" : 123}
]

CORRECT usage according to spec : 
[
{ op : "add", path : "/a", "value" : "{b : 123}"}
]
```

Is that correct? I can see that being the case, and certainly I would think that would be what a "diff" generator on the client side would generate. Since the first thing it would trip over would be the fact that "a" was null in the original document, and not so in the destination state. E.g. Using a C# diff generator (https://github.com/mindingdata/dotnetdiff), that's what it would output. 

I would possibly do this in a different pull request as I assume there will be a bit of work to do to "serialize" the json string "value" into an object in the pathhelper.

**Comment by sergkr** [comment]
Based on my understanding of the spec, I believe your example is correct - with the exception that there's no need for quotes around the value (as that would indicate the value is a literal string, whereas we want an object):

    { op : "add", path : "/a", "value" : {b : 123}}

A related question: what if we try to add an entry to an array, but the array itself does not exist?  For example:

    Existing object: 
    { "q": { "bar": 2 } }

    PATCH document:
    [
    { op : "add", path : "/a/0", "value" : "one"}
    ]

Should this be an error? Or should we instantiate the array and add the item? This question was raised on stackoverflow here:

http://stackoverflow.com/questions/15930516/interpretation-of-the-json-patch-spec

The answer there was that should be an error (you can't add to an array that does not yet exist). You would have to do this instead:

    [
    { op : "add", path : "/a", "value" : ["one"] }
    ]

I'll play around and see how much work it's going to take to implement this. I think I'll do this one before #11, and I'll create separate pull requests.

**Comment by sergkr** [comment]
Here's another question... if we're dealing with an add/remove operation on an array, we currently go through a lot of trouble to grow or shrink the array, copy over all the items from the old array, etc. This may be contrary to expectation. The primary use case for choosing an array (as opposed to a list) in the first place is that it's *supposed to be fixed in size*. If the user wanted a collection that could grow and shrink, they would choose a list instead.  I wonder if it makes sense to simply error out if we're doing an add/remove on an array?

**Comment by myquay** [comment]
I've re-read that portion of the spec and you're absolutely right. 

The [spec mentions](https://tools.ietf.org/html/rfc6902#section-4.1) that the only valid targets are

1. The root of the target document
2. A member to add to an existing object
3. An element to add to an existing array

One clear deviation is that currently we don't allow 1 or 2 as we only support strongly typed objects so it doesn't make sense to allow users to change the structure of the object.

But we shouldn't be going around instantiating defaults either. Based on your recommendations I think we can break this issue up in to a few components.

**Update the path helper**

* Update the test case to expect the correct behaviour (e.g. an error if setting a member on an object does not exist)
* Update the path helper to throw an error rather than instantiating an object

**Fully support complex value types in the operations**

I haven't fully tested the support for complex objects in the "value" portion of the patch operation but it shouldn't be too hard to bring up to scratch

* Update test cases to cover adding complex types
* Make any changes required to fully support this scenario

**Array behaviour with different underlying collections**

I actually think this is the most interesting point raised, as it's got to do with how much of the underlying C# implementation that we let leak through. 

We have already left out parts of the specification that require the underlying type to change (e.g. add a new member), but as you mentioned arrays are usually an array for a reason - in that they're a fixed size. Now JSONPatch doesn't differentiate between fixed and dynamic collections, but just as we expect the user to have prior knowledge about the structure of the object it isn't much of a stretch to extend that to the underlying implementation of the collection they're modifying.

I'm leaning more towards throwing an error if we try change the size of an array simply because an application that is using the library might be expecting the arrays to remain a fixed size and it'd be rude to surprise them.

I'll probably look at tidying this up mid-week but I'm happy to accept a pull request if you want to jump in.

**Comment by sergkr** [comment]
I'm pretty darn close to implementing all of the above changes, as well as the move operation (I have them sitting in my "WIP" branch on my fork, if you want to peek). I was hoping to finish by today, but it's  getting a bit late, and there are a couple more caveats with move, and I want to polish things up a bit. Hopefully, tomorrow I'll be ready to create pull requests (I'll split out the "move" related changes from the rest).

**Comment by sergkr** [comment]
Noticed another small issue with "add", which was hindering the implementation of "move": According to the spec, it should *not* be an error if the target location already has a value:

    o  If the target location specifies an object member that does exist,
       that member's value is replaced.

So "add" should just act like "replace" in that case.  However, the code is currently throwing an exception:

    if (operationType == JsonPatchOperationType.add && property.GetValue(entity) != null)
        throw new JsonPatchException("You are trying to perform an add operation on a property that already has a value.");

Why does that hinder the implementation of "move"?  Because a move is just a remove followed by an add:

    This operation is functionally identical to a "remove" operation on
    the "from" location, followed immediately by an "add" operation at
    the target location with the value that was just removed.

That's exactly how I'm planning on implementing it. But with the current code, that means we can only use "move" if the target location is null, which shouldn't be a requirement.

I'll be getting rid of that check in the pull request - just wanted to point out that this is a change from existing behavior.  The spec seems pretty clear on this one, but let me know if there are any issues.

**Comment by myquay** [comment]
#13 Looks good!
